### ISSUE TITLE
KSM limits

### ISSUE THREAD

**Issue by StefanescuCristian** [apbaxel/UKM#7]
The slider for KSM pages to scan should go to a maximum of a power of 2, not of 10. You can change it here: https://github.com/apbaxel/UKM/blob/UKM-Enhanced/data/UKM/config.json.generate.adv#L64

Also, the maximum scan delay is too low IMHO and should go to at least 3000ms. I keep my scan delay to 2500, for example.
You can find it here: https://github.com/apbaxel/UKM/blob/UKM-Enhanced/data/UKM/config.json.generate.adv#L73

Thank you!

**Comment by apbaxel** [comment]
Hey thanks for the feedback. I've changed the max scan delay to 3000ms but pages to scan you mean it shouldn't go higher than 2 so it should only have from 0-2?

**Comment by StefanescuCristian** [comment]
No, I mean IT should go with powers of 2. Like 256, 512, 1024, etc.

**Comment by apbaxel** [comment]
I've changed the max scan delay to 3000 but left pages to scan the way it was. All apps I've seen are using a max of 500 pages.

**Comment by StefanescuCristian** [comment]
I'm fine with it.
Thank you.
