### ISSUE TITLE
[regression] franco sound 

### ISSUE THREAD

**Issue by StefanescuCristian** [apbaxel/UKM#8]
I used v3.3.2 with no problem in setting sound tunables with franco sound, but after updating to 3.4.2, the tunables reset back to 0 after trying to apply them.

The problem is in the way the action "generic" interprets the variable $SC.
With the manually added path (/sys/class/misc/soundcontrol/), the action works, with the variable, it fails.

**Comment by StefanescuCristian** [comment]
This issue might be also related with this post from XDA:
http://forum.xda-developers.com/showpost.php?p=55389638&postcount=1724

**Comment by apbaxel** [comment]
Thanks, found the issue and it will be fixed in next version
