### ISSUE TITLE
CPU Boost Toggle

### ISSUE THREAD

**Issue by DespairFactor** [apbaxel/UKM#9]
Can you please add an option to toggle CPU Boost on and off?
Values are: Y for on and N for off
The nodes are:
/sys/module/cpu_boost/parameters/cpu_boost 
and 
/sys/module/cpu_boost/parameters/cpuboost_enable

**Comment by apbaxel** [comment]
cpu_boost was already there so I'll just add cpuboost_enable. Any special description you would like?

**Comment by DespairFactor** [comment]
Just needs to say something along the lines of toggle cpu boost on or off:P

**Comment by apbaxel** [comment]
Added, ready for next version. Thanks.
